### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by kr-viku** [arupadhyay25/DreamBaths-E-Commerce-App#44]
@Madhusudan0906 

1. in Navbar, except for top-offers no tab is showing content.
2. clear all btn for the filter is not working.
3. add to cart functionality not implemented
4. on the login page, validation is not implemented, and also functionality is not working.
5. product page is not visible

**Comment by arupadhyay25** [comment]
The deployment failed at render shifted to cyclic now all features are working now
